name: Secret Scan (Disabled)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Success step
        run: echo "✅ Workflow ran successfully (no secret scanning)"

